/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/xmudrii/certs-controller/pkg/apis/certcontroller/v1alpha1"
	scheme "github.com/xmudrii/certs-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SrvCertsGetter has a method to return a SrvCertInterface.
// A group's client should implement this interface.
type SrvCertsGetter interface {
	SrvCerts(namespace string) SrvCertInterface
}

// SrvCertInterface has methods to work with SrvCert resources.
type SrvCertInterface interface {
	Create(*v1alpha1.SrvCert) (*v1alpha1.SrvCert, error)
	Update(*v1alpha1.SrvCert) (*v1alpha1.SrvCert, error)
	UpdateStatus(*v1alpha1.SrvCert) (*v1alpha1.SrvCert, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.SrvCert, error)
	List(opts v1.ListOptions) (*v1alpha1.SrvCertList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SrvCert, err error)
	SrvCertExpansion
}

// srvCerts implements SrvCertInterface
type srvCerts struct {
	client rest.Interface
	ns     string
}

// newSrvCerts returns a SrvCerts
func newSrvCerts(c *CertcontrollerV1alpha1Client, namespace string) *srvCerts {
	return &srvCerts{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the srvCert, and returns the corresponding srvCert object, and an error if there is any.
func (c *srvCerts) Get(name string, options v1.GetOptions) (result *v1alpha1.SrvCert, err error) {
	result = &v1alpha1.SrvCert{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("srvcerts").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SrvCerts that match those selectors.
func (c *srvCerts) List(opts v1.ListOptions) (result *v1alpha1.SrvCertList, err error) {
	result = &v1alpha1.SrvCertList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("srvcerts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested srvCerts.
func (c *srvCerts) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("srvcerts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a srvCert and creates it.  Returns the server's representation of the srvCert, and an error, if there is any.
func (c *srvCerts) Create(srvCert *v1alpha1.SrvCert) (result *v1alpha1.SrvCert, err error) {
	result = &v1alpha1.SrvCert{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("srvcerts").
		Body(srvCert).
		Do().
		Into(result)
	return
}

// Update takes the representation of a srvCert and updates it. Returns the server's representation of the srvCert, and an error, if there is any.
func (c *srvCerts) Update(srvCert *v1alpha1.SrvCert) (result *v1alpha1.SrvCert, err error) {
	result = &v1alpha1.SrvCert{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("srvcerts").
		Name(srvCert.Name).
		Body(srvCert).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *srvCerts) UpdateStatus(srvCert *v1alpha1.SrvCert) (result *v1alpha1.SrvCert, err error) {
	result = &v1alpha1.SrvCert{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("srvcerts").
		Name(srvCert.Name).
		SubResource("status").
		Body(srvCert).
		Do().
		Into(result)
	return
}

// Delete takes name of the srvCert and deletes it. Returns an error if one occurs.
func (c *srvCerts) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("srvcerts").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *srvCerts) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("srvcerts").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched srvCert.
func (c *srvCerts) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SrvCert, err error) {
	result = &v1alpha1.SrvCert{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("srvcerts").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
