/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/xmudrii/certs-controller/pkg/apis/certs/v1alpha1"
	scheme "github.com/xmudrii/certs-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CABundlesGetter has a method to return a CABundleInterface.
// A group's client should implement this interface.
type CABundlesGetter interface {
	CABundles(namespace string) CABundleInterface
}

// CABundleInterface has methods to work with CABundle resources.
type CABundleInterface interface {
	Create(*v1alpha1.CABundle) (*v1alpha1.CABundle, error)
	Update(*v1alpha1.CABundle) (*v1alpha1.CABundle, error)
	UpdateStatus(*v1alpha1.CABundle) (*v1alpha1.CABundle, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.CABundle, error)
	List(opts v1.ListOptions) (*v1alpha1.CABundleList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CABundle, err error)
	CABundleExpansion
}

// cABundles implements CABundleInterface
type cABundles struct {
	client rest.Interface
	ns     string
}

// newCABundles returns a CABundles
func newCABundles(c *CertcontrollerV1alpha1Client, namespace string) *cABundles {
	return &cABundles{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cABundle, and returns the corresponding cABundle object, and an error if there is any.
func (c *cABundles) Get(name string, options v1.GetOptions) (result *v1alpha1.CABundle, err error) {
	result = &v1alpha1.CABundle{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cabundles").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CABundles that match those selectors.
func (c *cABundles) List(opts v1.ListOptions) (result *v1alpha1.CABundleList, err error) {
	result = &v1alpha1.CABundleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cabundles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cABundles.
func (c *cABundles) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("cabundles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a cABundle and creates it.  Returns the server's representation of the cABundle, and an error, if there is any.
func (c *cABundles) Create(cABundle *v1alpha1.CABundle) (result *v1alpha1.CABundle, err error) {
	result = &v1alpha1.CABundle{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("cabundles").
		Body(cABundle).
		Do().
		Into(result)
	return
}

// Update takes the representation of a cABundle and updates it. Returns the server's representation of the cABundle, and an error, if there is any.
func (c *cABundles) Update(cABundle *v1alpha1.CABundle) (result *v1alpha1.CABundle, err error) {
	result = &v1alpha1.CABundle{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cabundles").
		Name(cABundle.Name).
		Body(cABundle).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *cABundles) UpdateStatus(cABundle *v1alpha1.CABundle) (result *v1alpha1.CABundle, err error) {
	result = &v1alpha1.CABundle{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cabundles").
		Name(cABundle.Name).
		SubResource("status").
		Body(cABundle).
		Do().
		Into(result)
	return
}

// Delete takes name of the cABundle and deletes it. Returns an error if one occurs.
func (c *cABundles) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cabundles").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cABundles) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cabundles").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched cABundle.
func (c *cABundles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CABundle, err error) {
	result = &v1alpha1.CABundle{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("cabundles").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
